name: Deploy Build via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Deploy build
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          protocol: ${{ secrets.HOSTINGER_PROTOCOL }}
          local-dir: ./dist/
          server-dir: /domains/movvewallet.pro/public_html/
